#!/usr/bin/perl
#
##############################################################################
#
# File Name:    ress.pl
# Author:       Ion CIONCA (Ion.Cionca@epfl.ch) - 2005
#
#########################################################################
#####
#
#


use lib '/opt/dinfo/lib/perl';

use strict;
use Tequila::Client;
use payonline_tools;

use vars qw(%args $lang $errmsg $crtdate $sciper $key $tequila);

use utf8;
binmode(STDOUT, ":utf8");

my $me 			= $ENV {SCRIPT_NAME};
my $us 			= $ENV {SERVER_NAME};
my $qs 			= $ENV {QUERY_STRING};
my $pi 			= $ENV {PATH_INFO};
my $lang 		= 'fr';
my @languages 	= ('fr','en');
my $mailresp	= 'ion.cionca@epfl.ch';
my $masterIP	= '128.178.1.146';
my $accesslist	= '104782,213338,273001,242631,293099';
my $URL			= '/cgi-bin/formcont/admin';

my $DEBUG 				 = '1';
$payonline_tools::DEBUG	 = $DEBUG;

init();
authenticate ();

payonline_tools::header ();
  
error ('Accès réservé', 1) unless $accesslist =~ /$sciper/;

print qq{
	<b>Actions</b><br>
	<li style="margin-left: 20px;"><a href="$URL/prix">gestion des prix</a></li>
	<li style="margin-left: 20px;"><a href="$URL/transact">transactions</a></li>
	<hr>
};

prix () 	if $pi =~/prix/;
detail () 	if $pi =~/detail/;

transact ();

exit;

#------
sub init {
  %args		= payonline_tools::loadargs ();
  $crtdate 	= payonline_tools::getcrtdate();
}


#------
sub prix {

	print qq{<h4>Gestion des prix</h4>
	<form name="form" action="$URL/prix?op=add" method="post" style="margin-bottom: 0;">
	<li style="margin-left: 20px;">ajouter un prix : <input name="prix"> CHF (<em>xxx.yy</em>)</li>
	</form>
	<br>
	<em>Cliquer sur <b>x</b> pour annuler le montant</em><br>
	};
	
	my $sql = qq{select montant from prix order by montant + 0};
	my $sth = payonline_tools::dbquery ($sql);
	my $prix;
	while (my ($montant) = $sth->fetchrow) {
		next unless $montant;
		$prix->{$montant} = 1;
	}
	
	if ($args{op} eq 'add') {
		error ("prix absent") 		unless $args{prix};
		error ("prix déjà saisi") 	if defined $prix->{$args{prix}};

		my $sql = qq{insert into prix set montant='$args{prix}'};
		payonline_tools::dbquery ($sql);
		$prix->{$args{prix}} = 1;
	}
	if ($args{op} eq 'del') {
		error ("prix absent") 		unless $args{prix};
		my $sql = qq{delete from prix where montant='$args{prix}'};
		my $sth = payonline_tools::dbquery ($sql);
		delete $prix->{$args{prix}};
	}

	foreach my $montant (sort {$a <=> $b} keys %$prix) {
		print qq{<div style="width:200px; text-align: right;">$montant [ <a href="$URL/prix?op=del&prix=$montant">x</a> ]</div>};
	}

  footpage ();

}

#------
sub detail {

  error (qq{identificateur de transaction absent}) unless $args{id};

  my $sql = qq{select * from transact where id='$args{id}'};
  print qq{
   <b>Détails transaction</b>
  };

  my $sth = payonline_tools::dbquery ($sql);
  error (qq{erreur accès database}) unless $sth;
  my $data = $sth->fetchrow_hashref();
  error (qq{transaction inconnue}) unless $data->{id};
  
  print qq{
  	<table width="100%" cellpadding=0 border=0> 
	 <tr><td>id. transaction</td><td>$data->{id}</td></tr>
	 <tr><td>Nom</td><td>$data->{name}</td></tr>
	 <tr><td>Prénom</td><td>$data->{firstname}</td></tr>
	 <tr><td>Adresse</td><td>$data->{addr}</td></tr>
	 <tr><td>Ville</td><td>$data->{zip}&nbsp;$data->{city}</td></tr>
	 <tr><td>Pays</td><td>$data->{country}</td></tr>
	 <tr><td>email</td><td>$data->{email}</td></tr>
	 <tr><td>no.cours</td><td>$data->{nocours}</td></tr>
	 <tr><td>no.facture</td><td>$data->{nofacture}</td></tr>
	 <tr><td>no.pernum</td><td>$data->{nopernum}</td></tr>
	 <tr><td>montant</td><td>$data->{amount} CHF</td></tr>
	 <tr><td>état transaction</td><td>$data->{etat}</td></tr>
	 <tr><td>PaymentID</td><td>$data->{PaymentID}</td></tr>
	 <tr><td>Mode paiement</td><td>$data->{paymode}</td></tr>
	 <tr><td>Date paiement</td><td>$data->{datecr}</td></tr>

    </table>
  };

  footpage ();

}

sub footpage {
	print qq{
		<hr>
		<span class="copy">&copy; 2011 - <a href="http://www.formation-continue-unil-epfl.ch/" target="_blank">Formation continue UNIL-EPFL</a></span>
	};
	exit;

}

#------
sub transact {

  print qq{
<!--
   <form action=$me/search method=POST>
   <b>Recherche transactions</b> par 
   <table >
   <tr><td align=right>nom : <td><input name=name width=32></tr>
   <tr><td align=right>id.transaction : <td><input name=id width=32></tr>
   <tr><td align=right>no.facture :  <td><input name=id width=32></trr>
   <tr><td align=right>no.facture :  <td><input name=id width=32></tr>
   </table>
   <input type=submit name=go value=chercher>
   </form>
   <p></p>
-->
   <b>Transactions :</b> <a href=$me?etat=payé>payées</a> | <a href=$me?etat=all>toutes les transactions</a>
   <br>
   <br>
  };

  $args{etat} = 'payé' unless $args{etat};

  my $sql = qq{select * from transact };
    $sql .= qq{where etat='$args{etat}'} if $args{etat} eq 'payé';
  my $txt = $args{etat} eq 'payé' ? qq{transactions payées} : qq{toutes les transactions};
  print qq{
   <b>$txt</b>
  };
  $sql 	 .= qq{ order by datecr desc, name, firstname};
  my $sth = payonline_tools::dbquery ($sql);
  error (qq{erreur accès database}) unless $sth;
  print qq{
  <table width="100%" cellpadding=0 border=0>
    <tr>
    <td>Nom
    <td>Adresse
    <td>No. commande 
    <td width=200>Date
    <td>Montant
    <td>Etat
   </tr>
  };
  while (my $data = $sth->fetchrow_hashref()) {
  	print qq{
  		<tr>
  		  <td><a href=$me/detail?id=$data->{id}>$data->{name}&nbsp;$data->{firstname}</a></td>
  		  <td>$data->{addr}&nbsp;$data->{zip}, $data->{city},$data->{country}&nbsp;</td>
  		  <td>$data->{id}</td>
  		  <td>$data->{datecr}</td>
  		  <td>$data->{amount}</td>
  		  <td>$data->{etat}</td>
  		</tr>
  	};
  }

  print qq{
    </table>
	<hr>
	<span class="copy">&copy; 2011 - <a href="http://www.formation-continue-unil-epfl.ch/" target="_blank">Formation continue UNIL-EPFL</a></span>

  };
	
  footpage ();
}

sub error {
	my ($txt, $exit) = @_;
	return unless $txt;
	print qq{
	<h2>erreur</h2>
	$txt
	<br>
	};
	
	footpage ();
}

#------
sub authenticate {

  unless ($tequila) {
    $tequila = new Tequila::Client ();
    $tequila->init ();
  } 

  $tequila->setclientsesskey ($key) if $key;
  $tequila->setservice  	('Formcont : admin paiement en ligne');
  $tequila->setidentities 	('any');
  $tequila->request     	('name','firstname','uniqueid');

  $tequila->authenticate ();

  $key 		= $args {key};
  $sciper 	= $tequila->{attrs}->{uniqueid};

}
