#!/usr/bin/perl
#
##############################################################################
#
# File Name:    ress.pl
# Author:       Ion CIONCA (Ion.Cionca@epfl.ch) - 2005
#
#########################################################################
#####
#
#


use strict;
use lib '/var/www/vhosts/payonline.epfl.ch/cgi-bin/formcont/test';
use payonline_tools;

$payonline_tools::DEBUG	 = 1;

warn "getPrix..\n";

print qq{Content-Type: text/plain; charset=iso-8859-1
Access-Control-Allow-Origin: *\n\n};

my $sql = qq{select montant from prix order by montant + 0};
my $sth = payonline_tools::dbquery ($sql);

print qq{
<select name="Total">
<option value="">--</option>
};

while (my ($montant) = $sth->fetchrow) {
	print qq{<option value="cours:$montant">$montant CHF</option>};
#warn " >> $montant\n";
}
print qq{
</select >
};
