#!/usr/bin/perl
#
##############################################################################
#
# File Name:    ress.pl
# Author:       Ion CIONCA (Ion.Cionca@epfl.ch) - 2005
#
#########################################################################
#####
#
#


use strict;
use payonline_tools;
use formcont_tools;

use utf8::all;
binmode(STDOUT, ":utf8");

$payonline_tools::DEBUG	 = 1;

log_event("getPrix");

print qq{Content-Type: text/plain; charset=UTF-8
Access-Control-Allow-Origin: *\n\n};

my $sql = qq{select montant from prix order by montant + 0};
my $sth = formcont_tools::dbquery ($sql);

print qq{
<select name="Total">
<option value="">--</option>
};

while (my ($montant) = $sth->fetchrow) {
	print qq{<option value="cours:$montant">$montant CHF</option>};
# log_event "getPrix", montant => $montant;
}
print qq{
</select >
};
