#!/usr/bin/perl
#
##############################################################################
#
# File Name:    ress.pl
# Author:       Ion CIONCA (Ion.Cionca@epfl.ch) - 2005
#
#########################################################################
#####
#
#


use strict;
use payonline_tools;

use vars qw(%args $tmpldir $lang $errmsg $crtdate $lang);

my $me 			= $ENV {SCRIPT_NAME};
my $us 			= $ENV {SERVER_NAME};
my $qs 			= $ENV {QUERY_STRING};
my $pi 			= $ENV {PATH_INFO};
my $mailresp	= 'ion.cionca@epfl.ch';
my $masterIP	= '128.178.1.146';

my %errmsgs	= (
	fr => [
		'Erreur(s) de saisie',
		'<li>indentificateur d\'instance absent</li>',
		'<li>indentificateur de monnaie absent</li>',
		'<li>montant formation absente</li>',
		'<li>nom absent</li>',
		'<li>prénom absent</li>',
		'<li>adresse absente</li>',
		'<li>code postal absent</li>',
		'<li>ville absente</li>',
		'<li>code pays absent</li>',
		'Veuillez retourner sur la page précédente pour effectuer les corrections nécessaires.',
		'<li>total transaction incorrect</li>',
		'Instance de paiement pas trouvée ou pas active',
		'Veuillez retourner sur la page précédente et suivre le lien de contact pour plus de détails.',
		'<li>les seules monnaies acceptées : CHF, EUR, USD</li>',
		' *** Attention : version de test. Ne pas utiliser, svp ! ***',			# 15
		'Le service <b>payonline@epfl</b> est momentanément indisponible : veuillez rester sur cette page et l\'actualiser dans quelques minutes',			# 16

		'<li>numéreo pernum absent</li>',
		'<li>numéro de facture absent</li>',
		'<li>numéro du cours absent</li>',
		'<li>email absent</li>',
		'<li>syntaxe email incorrecte</li>',
	      ],
	en => [
		'Input error(s)',								# 0
		'<li>instance identificator missing</li>',		# 1
		'<li>currency missing</li>',					# 2
		'<li>trainig fee missing</li>',					# 3
		'<li>last name missing</li>',					# 4
		'<li>first name missing</li>',					# 5
		'<li>address missing</li>',						# 6
		'<li>zip code missing</li>',					# 7
		'<li>city missing</li>',						# 8
		'<li>country code missing</li>',				# 9
		'Please return on the previous page and correct the input',	# 10
		'<li>wrong total format</li>',					# 11
		'Payment instance not found or not operational',		# 12
		'Please return on the previous page and follow the contact link for details',		# 13
		'<li>valid currencies : CHF, EUR, USD</li>',			# 14
		' *** Warning : test version. Not for public usage ! ***',	# 15
		'<b>payonline@epfl</b> is currently unavailable : please stay on this page end do a page reload in a couple of minutes.',	# 16
		'<li>pernum number missing</li>',
		'<li>invoice number missing</li>',
		'<li>training number missing</li>',
		'<li>email missing</li>',
		'<li>incorrect email syntax</li>',
	      ],
	);

  %args		= payonline_tools::loadargs ();
  $crtdate 	= payonline_tools::getcrtdate();
  $lang 	= $args{lang} ? $args{lang} : 'en' ;
  
warn "--> formcont payment : $payonline_tools::mode\n";

  payonline_tools::header ();

  main ();

  payonline_tools::footer ();

  exit;


#------
sub main {

  # - check params
  $errmsg .= "$errmsgs{$lang}->[4]<br>" 	unless $args{LastName};
  $errmsg .= "$errmsgs{$lang}->[5]<br>" 	unless $args{FirstName};
  $errmsg .= "$errmsgs{$lang}->[7]<br>" 	unless $args{Zip};
  $errmsg .= "$errmsgs{$lang}->[8]<br>" 	unless $args{City};
  $errmsg .= "$errmsgs{$lang}->[6]<br>" 	unless $args{Addr};
  $errmsg .= "$errmsgs{$lang}->[9]<br>" 	unless $args{Country};

  $errmsg .= "$errmsgs{$lang}->[17]<br>" 	unless $args{nopernum};
  $errmsg .= "$errmsgs{$lang}->[18]<br>" 	unless $args{nofacture};
#  $errmsg .= "$errmsgs{$lang}->[19]<br>" 	unless $args{nocours};

  $errmsg .= "$errmsgs{$lang}->[20]<br>" 	unless $args{Email};
  if ($args{Email}) {
	  # - validation email
	  $errmsg .= "$errmsgs{$lang}->[21]<br>" unless ($args{Email} =~ /^(\w|\-|\_|\.)+\@((\w|\-|\_)+\.)+[a-zA-Z]{2,}$/);
  }
  # validation du total:  [0-9]{0,9}\.[0-9]{1,2}
  my ($raison, $UserTotal) = split (/:/, $args{Total});
  $errmsg .= "$errmsgs{$lang}->[3]<br>" 	unless $UserTotal;

  error ($errmsg) if $errmsg;
  
  payonline_tools::setYellowPaySrv();

  my $ParamTotal = $UserTotal * 100;	# 		- pas de décimales
  my $currency   = 'CHF';
  my $userdata   = {
  	name 	  	=> $args{LastName},
  	firstname 	=> $args{FirstName},
  	addr 	  	=> $args{Addr},
  	zip 	  	=> $args{Zip},
  	city 	  	=> $args{City},
  	country	  	=> $args{Country},
	email 	  	=> $args{Email},
	amount 	  	=> $UserTotal,
	raison 	  	=> $raison,
  	nopart    	=> $args{num_part},
  	nofacture 	=> $args{num_facture},
  	nocours	  	=> $args{nocours},
	id_transact => $args{id_transact},
  };
  
  my $id_trans 	= payonline_tools::gentablekey($userdata);

warn " ==>> formcont payment : args dump <<==\n";
foreach my $item (keys %args) {
	warn "$item=$args{$item}\n";
}
 
  my $hashdata = {
	orderID 	=> $id_trans,
	amount 		=> $ParamTotal,
	PSPID 		=> $payonline_tools::ShopID,
  };

  my $txtHash = payonline_tools::makeHash ($hashdata, 'in');
  my $txtLang = $lang eq 'fr' ? 'fr_FR' : 'en_US';
  my $COM 	  = qq{Payement en ligne : Formation continue UNIL/EPFL};
  my $LOGO 	  = qq{http://www.formation-continue-unil-epfl.ch/images/logo.png};
  
  print qq{
	   <form action="$payonline_tools::YellowPaySrv" method="POST" name="cmd" >

			<input type="hidden" name="PSPID" 		value="$payonline_tools::ShopID"> 
			<input type="hidden" name="orderID" 	value="$id_trans"> 
			<input type="hidden" name="amount" 		value="$ParamTotal"> 
			<input type="hidden" name="currency" 	value="CHF"> 
			<input type="hidden" name="language" 	value="$txtLang"> 
			<input type="hidden" name="SHASign" 	value="$txtHash"> 

			<input type="hidden" name="CN" 			value="$args{FirstName} $args{LastName}"> 
			<input type="hidden" name="EMAIL" 		value="$args{Email}"> 
			<input type="hidden" name="ownertown" 	value="$args{City}"> 
			<input type="hidden" name="COM" 		value="$COM"> 
			<input type="hidden" name="LOGO" 		value="$LOGO"> 
  };
  if ($lang eq 'fr') {
  	print qq{
		   <h2>Paiement en-ligne</h2>
			   <p> Les informations vous concernant sont enregistrées.</p>
			   <p>Pour conclure le paiement du montant de <b>$UserTotal&nbsp;CHF</b>, veuillez cliquer sur le bouton <b>Effectuer le paiement</b> pour acc&eacute;d&eacute;r au service
			   de paiement en ligne de PostFinance et finaliser l'opération

			   <br><p>Les moyens de paiement disponibles sont :</p>
			   <ul>
				<li>PostFinance Card</li>
				<li>EUROCARD/MasterCard</li>
				<li>Visa  </li>
			   </ul>		

		   		<p>
		   		<input type="submit" name="go" value="Effectuer le paiement">&nbsp;de <b>$UserTotal&nbsp;CHF</b> 
			    <p></p>
			    </p>
			    
			   <b>Attention : </b>
			   <li>vous allez quitter le site de la Formation continue UNIL/EPFL pour celui de Postfinance
			   <li>pour garantir le processus de paiement en ligne, vous devez suivre chaque étape comme indiqué, sans jamais fermer les fenêtres du navigateur
			   <li>la saisie de données qui suit a lieu au travers d'une connexion sécurisée qui encrypte les informations transmises ; vous pouvez cliquer sur le cadenas affiché par le navigateur pour vérifier le certificat de sécurité de Postfinance

		</form>
	};
  } else {
  	print qq{
		   <h2>Pay on line</h2>
			   <p>The information you provided has been saved.</p>
			   <p>Please click on the "Proceed to pay" button in order to pay the bill of <b>$UserTotal&nbsp;CHF</b>, proceed to Postfinance's pay on line service and finish the transaction
		
			   <p>You may pay by :</p>
			   <ul>
				<li>PostFinance Card</li>
				<li>EUROCARD/MasterCard</li>
				<li>Visa  </li>
			   </ul>		
		 
		   		<p>
		   		<input type="submit" name="go" value="Proceed to pay">&nbsp; <b>$UserTotal&nbsp;CHF</b> 
			    <p></p>
			    </p>
			    
			   <b>Note : </b>
			   <li>you will leave now the <b>Formation continue UNIL/EPFL</b> form and will be directed to Postfinance's on line payment service
			   <li>do observe the steps proposed by the payment procedure and do not close the browser
			   <li>the connection to Postfinance is secured ; you may check the locker icon which guarantees the secure transaction

		</form>
	};
  
  }

}

sub error {
	my ($txt) = @_;
	return unless $txt;
	
	my $errtxt1 = qq{erreur};
	my $errtxt2 = qq{Veuillez effectuer les corrections nécessaires sur la page précédente};
	if ($lang eq 'en') {
		$errtxt1 = qq{error};
		$errtxt2 = qq{Back on the previous page and fix these errors};
	}
	print qq{
	<h2>$errtxt1</h2>
	$txt
<br>
<b>$errtxt2</b>	
	};
	exit;
}