version: '3.4'

services:
  web:
    build: .
    hostname: dev-payonline
    ports:
      - "8080:8080"
    links:
      - mysql_payonline
    environment:
      - TEQUILA_HOST=test-tequila.epfl.ch
      - MOCK_ORACLE=1
      - SITE_URL=localhost:8080

  mysql_payonline:
    image: mysql:5.5
    hostname: mysql-payonline
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=accred
      - MYSQL_USER=payonline
      - MYSQL_PASSWORD=payonline
    volumes:
      - ./conf/docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - "23306:3306"