#!/usr/bin/perl
#
##############################################################################
#
# File Name:    ress.pl
# Author:       Ion CIONCA (Ion.Cionca@epfl.ch) - 2005
#
#########################################################################
#####
#
#

use lib '/var/www/accred';
use lib '/var/www/cgi-bin';
use lib '/var/www/html/payonline/cgi-bin';
#use lib '/var/www/html/payonline/cgi-bin/dev';

use strict;
use payonline_tools;

use vars qw(%args $tequila $key $sciper $email $nom $prenom $respunits 
	$tmpldir $lang $errmsg %CFs $crtdate
	);

use utf8;
binmode(STDOUT, ":utf8");

my $me 			= $ENV {SCRIPT_NAME};
my $us 			= $ENV {SERVER_NAME};
my $qs 			= $ENV {QUERY_STRING};
my $pi 			= $ENV {PATH_INFO};
my $lang 		= 'fr';
my $tmpldir 	= '/var/www/html/payonline/XX/tmpl/';
my $logfile		= '/var/log/httpd/payonline.log';
my @languages 	= ('fr','en');
my $mailresp	= 'ion.cionca@epfl.ch';
my @statlist	= ('test','prod');
my %errmsgs	= (
	fr => [
		'Erreur(s) de saisie',
		'Veuillez retourner sur la page précédente pour effectuer les corrections nécessaires.',
		'pas trouvée ou inactive',
		'<li>Date début absent ou erronée</li>',
		'<li>Description absente</li>',
		'<li>Fonds absent</li>',
		'<li>Centre financier absent</li>',
		'<li>Date fin absente ou erronée</li>',
		'<li>La date de fin doit être après la date début</li>',
		'<li>Compte budgétaire absent</li>',
		'<li>Date fin obligatoire</li>',
		'<li>Opération inconnue</li>',
		'Transactions payées',
		'Transactions non payées',
	      ],
	en => [
		'Input error(s)',												# 0
		'Please return on the previous page and correct the input',		# 1
		'pas trouvée ou inactive',										# 2
		'<li>Start date missing or wrong format</li>',					# 3
		'<li>Description missing</li>',									# 4
		'<li>Fund missing</li>',										# 5
		'<li>Financial center missing</li>',							# 6
		'<li>End date missing or wrong format</li>',					# 7
		'<li>End date must be after Start date</li>',					# 8
		'<li>Compte budgétaire missing</li>',							# 9
		'<li>End date is compulsory</li>',								# 10
		'<li>Unknown operation</li>',									# 11
		'Transactions payed',									# 12
		'Transactions not payed',								# 13
	      ],
	);
my %nat_comptable = (
		fr => {
			'', '---choisir---',
			'740055', '740055 : Vente, Formation continue',
			'740060', '740060 : Congrès, Séminaires, Conférences',
			'710100', '710100 : Candidatures bachelor et master',
			'710130', '710130 : Amendes bachelor et master',
			'710140', '710140 : Taxes certifications conformes',
			'700060', '700060 : Ventes de reprographie',
			},
		en => {
			'', '---select---',
			'740055', '740055 : Sales, Continuing Education',
			'740060', '740060 : Congres, Seminaires, Conferences',
			'710100', '710100 : Candidatures bachelor et master',
			'710130', '710130 : Amendes bachelor et master',
			'710140', '710140 : Taxes certifications conformes',
			'700060', '700060 : Ventes de reprographie',
			},
			);
			
print "Content-Type: text/html; charset=UTF-8\n\n";

%args		= payonline_tools::loadargs ();
warn "==== payonline :: tstscript ====";
 payonline_tools::debug_params (\%args);
warn "==== payonline :: tstscript ====";
